### ISSUE TITLE
Issues with contentType="blob"

### ISSUE THREAD

**Issue by saoron** [sneas/ionic-native-http-connection-backend#25]
Hi,
It looks like this plugin is having problem with request with contentType="blob"
I've submitted a PR regarding contentType="text" but with this one it looks to go deeper into the native code.

## example
 
	loadImageSync(url) {
			return new Promise((resolve, reject) => {
				this.http.get(url, { responseType: 'blob' })
					.map(blob => {
						var urlCreator = window.URL;
						return this.sanitizer.bypassSecurityTrustUrl(urlCreator.createObjectURL(blob));
					})
					.subscribe(
						response => {
							resolve(response)
						},
						e => reject(e)
					)
			});
		}

---

    this.loadImageSync('https://www.google.com/images/errors/robot.png').then(
        url =>  {this.imgSrc = url}
    )

---

    <img [src]="imgSrc" />

> This is what Xcode says
![image](https://user-images.githubusercontent.com/4144775/33884801-db3d210e-df49-11e7-8504-33482a2eeaea.png)

Thanks,

**Comment by sneas** [comment]
Hi, thanks a lot for the report. It turned out there are more problems with the library so this PR https://github.com/sneas/ionic-native-http-connection-backend/pull/24 has been created which fixes blobs and texts at once also does the correct error handling. It will be merged as soon as CI build is fixed (ETA half an hour).

Thanks again for all the reports.

**Comment by saoron** [comment]
Thank you!

**Comment by sneas** [comment]
v4.0.1 has been released. Feel free to (re)open the issue in case of any troubles.

**Comment by saoron** [comment]
Hi @sneas, Sorry but the blob issue is still here.
the 4.0.1 release did fix the contecType="text" issue.

**Comment by sneas** [comment]
Looks like cordova plugin crashes on blobs. Apparently this is the issue for https://github.com/silkimen/cordova-plugin-advanced-http
